[package]
name = "gayming"
version = "0.1.0"
edition = "2024"

[dependencies]
avian3d = "0.2.0"
bevy = { version = "0.15.1", features = ["wayland"] }
bevy-inspector-egui = "0.28.1"
blenvy = { git="https://github.com/jwright159/Blenvy.git" }
